In [2]:
import pandas as pd

In [5]:
df_plataforma = pd.read_csv("estudiantes_cursos.csv")
df_plataforma

,ID_Estudiante,Curso,Nivel_Educativo,Horas_Estudio,Lecciones_Completadas,Puntaje_Evaluacion,Modalidad,Certificado_Generado
0,EST-2001,Arquitectura Cloud,Profesional,20.0,26,82.0,Híbrido,Sí
1,EST-2002,Desarrollo Web,Técnico,10.0,27,NaN,Híbrido,Sí
2,EST-2003,Arquitectura Cloud,Técnico,40.0,25,90.0,Sincrónico,No
3,EST-2004,Desarrollo Web,Tecnólogo,20.0,55,68.0,Híbrido,Sí
4,EST-2005,Python para Datos,Técnico,50.0,46,45.0,Híbrido,No
...,...,...,...,...,...,...,...,...
1005,EST-2031,Python para Datos,Tecnólogo,25.0,26,82.0,Híbrido,Sí
1006,EST-2032,Inteligencia Artificial,Posgrado,40.0,34,NaN,Sincrónico,No
1007,EST-2033,Arquitectura Cloud,Técnico,20.0,15,75.0,Sincrónico,Sí
1008,EST-2034,Arquitectura Cloud,Técnico,15.5,13,82.0,Sincrónico,No
1009,EST-2035,Inteligencia Artificial,Posgrado,10.0,56,82.0,Asincrónico,Sí

In [ ]:
# Seleccionar una columna como Serie
puntajes = df_plataforma["Puntaje_Evaluacion"]

# Subconjunto bidimensional 
df_subconjunto = df_plataforma[
    ["Curso", "Modalidad", "Lecciones_Completadas"]
]

print(puntajes)
df_subconjunto

0       82.0
1        NaN
2       90.0
3       68.0
4       45.0
        ...
1005    82.0
1006     NaN
1007    75.0
1008    82.0
1009    82.0
Name: Puntaje_Evaluacion, Length: 1010, dtype: float64

                        Curso    Modalidad  Lecciones_Completadas
0          Arquitectura Cloud      Híbrido                     26
1              Desarrollo Web      Híbrido                     27
2          Arquitectura Cloud   Sincrónico                     25
3              Desarrollo Web      Híbrido                     55
4           Python para Datos      Híbrido                     46
...                       ...          ...                    ...
1005        Python para Datos      Híbrido                     26
1006  Inteligencia Artificial   Sincrónico                     34
1007       Arquitectura Cloud   Sincrónico                     15
1008       Arquitectura Cloud   Sincrónico                     13
1009  Inteligencia Artificial  Asincrónico                     56

[1010 rows x 3 columns]

In [31]:
fila = df_plataforma.loc[120]
fila

ID_Estudiante                      EST-2121
Curso                    Arquitectura Cloud
Nivel_Educativo                   Tecnólogo
Horas_Estudio                          15.5
Lecciones_Completadas                    12
Puntaje_Evaluacion                     55.0
Modalidad                        Sincrónico
Certificado_Generado                     Sí
Name: 120, dtype: object

In [32]:
# Eliminar todos los registros duplicados

df_duplicados = df_plataforma.drop_duplicates()
df_duplicados

,ID_Estudiante,Curso,Nivel_Educativo,Horas_Estudio,Lecciones_Completadas,Puntaje_Evaluacion,Modalidad,Certificado_Generado
0,EST-2001,Arquitectura Cloud,Profesional,20.0,26,82.0,Híbrido,Sí
1,EST-2002,Desarrollo Web,Técnico,10.0,27,NaN,Híbrido,Sí
2,EST-2003,Arquitectura Cloud,Técnico,40.0,25,90.0,Sincrónico,No
3,EST-2004,Desarrollo Web,Tecnólogo,20.0,55,68.0,Híbrido,Sí
4,EST-2005,Python para Datos,Técnico,50.0,46,45.0,Híbrido,No
...,...,...,...,...,...,...,...,...
995,EST-2996,Desarrollo Web,Profesional,10.0,56,98.0,Asincrónico,Sí
996,EST-2997,Desarrollo Web,Posgrado,25.0,60,45.0,Híbrido,Sí
997,EST-2998,Desarrollo Web,Posgrado,NaN,25,90.0,Asincrónico,Sí
998,EST-2999,Bases de Datos SQL,Posgrado,15.5,25,82.0,Sincrónico,No
999,EST-3000,Python para Datos,Profesional,20.0,27,NaN,Asincrónico,Sí

In [ ]:
# Filtrar estudiantes con más de 40 lecciones completadas

df_plataforma[df_plataforma["Lecciones_Completadas"] > 40]

,ID_Estudiante,Curso,Nivel_Educativo,Horas_Estudio,Lecciones_Completadas,Puntaje_Evaluacion,Modalidad,Certificado_Generado
3,EST-2004,Desarrollo Web,Tecnólogo,20.0,55,68.0,Híbrido,Sí
4,EST-2005,Python para Datos,Técnico,50.0,46,45.0,Híbrido,No
9,EST-2010,Python para Datos,Tecnólogo,20.0,45,82.0,Sincrónico,Sí
13,EST-2014,Arquitectura Cloud,Tecnólogo,10.0,46,82.0,Asincrónico,Sí
14,EST-2015,Bases de Datos SQL,Técnico,20.0,50,82.0,Sincrónico,Sí
...,...,...,...,...,...,...,...,...
993,EST-2994,Python para Datos,Profesional,15.5,60,68.0,Sincrónico,Sí
995,EST-2996,Desarrollo Web,Profesional,10.0,56,98.0,Asincrónico,Sí
996,EST-2997,Desarrollo Web,Posgrado,25.0,60,45.0,Híbrido,Sí
1003,EST-2029,Desarrollo Web,Tecnólogo,20.0,43,68.0,Asincrónico,Sí
1009,EST-2035,Inteligencia Artificial,Posgrado,10.0,56,82.0,Asincrónico,Sí

In [35]:
#Registros de estudiantes inscritos 
df_plataforma[df_plataforma["Curso"].isin(["Python para Datos", "Arquitectura Cloud"])]

,ID_Estudiante,Curso,Nivel_Educativo,Horas_Estudio,Lecciones_Completadas,Puntaje_Evaluacion,Modalidad,Certificado_Generado
0,EST-2001,Arquitectura Cloud,Profesional,20.0,26,82.0,Híbrido,Sí
2,EST-2003,Arquitectura Cloud,Técnico,40.0,25,90.0,Sincrónico,No
4,EST-2005,Python para Datos,Técnico,50.0,46,45.0,Híbrido,No
6,EST-2007,Python para Datos,Tecnólogo,50.0,12,75.0,Híbrido,Sí
9,EST-2010,Python para Datos,Tecnólogo,20.0,45,82.0,Sincrónico,Sí
...,...,...,...,...,...,...,...,...
1001,EST-2027,Arquitectura Cloud,Tecnólogo,10.0,8,68.0,Asincrónico,No
1002,EST-2028,Python para Datos,Profesional,25.0,5,68.0,Asincrónico,Sí
1005,EST-2031,Python para Datos,Tecnólogo,25.0,26,82.0,Híbrido,Sí
1007,EST-2033,Arquitectura Cloud,Técnico,20.0,15,75.0,Sincrónico,Sí
1008,EST-2034,Arquitectura Cloud,Técnico,15.5,13,82.0,Sincrónico,No

In [36]:
# Filtrar alumnos con puntajes entre 70.0 y 85.0

df_plataforma[
    df_plataforma["Puntaje_Evaluacion"].between(70.0, 85.0)
]

,ID_Estudiante,Curso,Nivel_Educativo,Horas_Estudio,Lecciones_Completadas,Puntaje_Evaluacion,Modalidad,Certificado_Generado
0,EST-2001,Arquitectura Cloud,Profesional,20.0,26,82.0,Híbrido,Sí
6,EST-2007,Python para Datos,Tecnólogo,50.0,12,75.0,Híbrido,Sí
7,EST-2008,Inteligencia Artificial,Técnico,25.0,37,75.0,Sincrónico,Sí
8,EST-2009,Inteligencia Artificial,Posgrado,10.0,30,82.0,Sincrónico,Sí
9,EST-2010,Python para Datos,Tecnólogo,20.0,45,82.0,Sincrónico,Sí
...,...,...,...,...,...,...,...,...
1004,EST-2030,Desarrollo Web,Tecnólogo,50.0,7,75.0,Asincrónico,No
1005,EST-2031,Python para Datos,Tecnólogo,25.0,26,82.0,Híbrido,Sí
1007,EST-2033,Arquitectura Cloud,Técnico,20.0,15,75.0,Sincrónico,Sí
1008,EST-2034,Arquitectura Cloud,Técnico,15.5,13,82.0,Sincrónico,No
1009,EST-2035,Inteligencia Artificial,Posgrado,10.0,56,82.0,Asincrónico,Sí

In [ ]:
# Filtrar por modalidad y horas de estudio

df_plataforma.query('Modalidad == "Asincrónico" and Horas_Estudio > 25')

,ID_Estudiante,Curso,Nivel_Educativo,Horas_Estudio,Lecciones_Completadas,Puntaje_Evaluacion,Modalidad,Certificado_Generado
29,EST-2030,Desarrollo Web,Tecnólogo,50.0,7,75.0,Asincrónico,No
43,EST-2044,Inteligencia Artificial,Tecnólogo,32.5,51,55.0,Asincrónico,Sí
46,EST-2047,Desarrollo Web,Tecnólogo,40.0,47,45.0,Asincrónico,Sí
64,EST-2065,Bases de Datos SQL,Posgrado,32.5,38,45.0,Asincrónico,No
80,EST-2081,Bases de Datos SQL,Posgrado,32.5,36,90.0,Asincrónico,Sí
...,...,...,...,...,...,...,...,...
951,EST-2952,Python para Datos,Tecnólogo,32.5,18,90.0,Asincrónico,Sí
969,EST-2970,Arquitectura Cloud,Tecnólogo,32.5,38,82.0,Asincrónico,Sí
987,EST-2988,Python para Datos,Posgrado,32.5,16,NaN,Asincrónico,Sí
990,EST-2991,Bases de Datos SQL,Posgrado,50.0,28,82.0,Asincrónico,Sí
1004,EST-2030,Desarrollo Web,Tecnólogo,50.0,7,75.0,Asincrónico,No

In [42]:
# Filtrar por nivel educativo y nombre del curso

df_plataforma[
    (df_plataforma["Nivel_Educativo"] == "Profesional") &
    (df_plataforma["Curso"].str.startswith("B"))
]

,ID_Estudiante,Curso,Nivel_Educativo,Horas_Estudio,Lecciones_Completadas,Puntaje_Evaluacion,Modalidad,Certificado_Generado
40,EST-2041,Bases de Datos SQL,Profesional,15.5,16,75.0,Híbrido,Sí
69,EST-2070,Bases de Datos SQL,Profesional,15.5,31,82.0,Sincrónico,Sí
105,EST-2106,Bases de Datos SQL,Profesional,15.5,44,55.0,Híbrido,Sí
116,EST-2117,Bases de Datos SQL,Profesional,32.5,9,90.0,Asincrónico,Sí
156,EST-2157,Bases de Datos SQL,Profesional,10.0,21,82.0,Sincrónico,Sí
186,EST-2187,Bases de Datos SQL,Profesional,25.0,52,55.0,Sincrónico,Sí
187,EST-2188,Bases de Datos SQL,Profesional,10.0,16,75.0,Asincrónico,Sí
220,EST-2221,Bases de Datos SQL,Profesional,20.0,29,90.0,Asincrónico,Sí
246,EST-2247,Bases de Datos SQL,Profesional,15.5,44,NaN,Híbrido,No
292,EST-2293,Bases de Datos SQL,Profesional,10.0,29,82.0,Asincrónico,No
323,EST-2324,Bases de Datos SQL,Profesional,25.0,30,68.0,Asincrónico,Sí
364,EST-2365,Bases de Datos SQL,Profesional,50.0,60,NaN,Asincrónico,Sí
382,EST-2383,Bases de Datos SQL,Profesional,40.0,50,90.0,Híbrido,No
422,EST-2423,Bases de Datos SQL,Profesional,20.0,14,82.0,Sincrónico,Sí
448,EST-2449,Bases de Datos SQL,Profesional,15.5,30,45.0,Híbrido,Sí
473,EST-2474,Bases de Datos SQL,Profesional,50.0,40,82.0,Sincrónico,Sí
493,EST-2494,Bases de Datos SQL,Profesional,25.0,19,82.0,Asincrónico,No
498,EST-2499,Bases de Datos SQL,Profesional,40.0,22,75.0,Sincrónico,Sí
510,EST-2511,Bases de Datos SQL,Profesional,15.5,25,82.0,Híbrido,No
527,EST-2528,Bases de Datos SQL,Profesional,20.0,9,82.0,Sincrónico,No
537,EST-2538,Bases de Datos SQL,Profesional,15.5,28,75.0,Sincrónico,Sí
546,EST-2547,Bases de Datos SQL,Profesional,32.5,56,82.0,Sincrónico,No
554,EST-2555,Bases de Datos SQL,Profesional,20.0,32,NaN,Sincrónico,Sí
571,EST-2572,Bases de Datos SQL,Profesional,NaN,6,55.0,Sincrónico,Sí
586,EST-2587,Bases de Datos SQL,Profesional,10.0,26,75.0,Sincrónico,Sí
596,EST-2597,Bases de Datos SQL,Profesional,25.0,60,68.0,Híbrido,No
600,EST-2601,Bases de Datos SQL,Profesional,15.5,58,75.0,Sincrónico,Sí
628,EST-2629,Bases de Datos SQL,Profesional,25.0,13,55.0,Híbrido,Sí
635,EST-2636,Bases de Datos SQL,Profesional,10.0,39,75.0,Híbrido,No
684,EST-2685,Bases de Datos SQL,Profesional,20.0,59,98.0,Híbrido,Sí
690,EST-2691,Bases de Datos SQL,Profesional,32.5,54,NaN,Sincrónico,Sí
734,EST-2735,Bases de Datos SQL,Profesional,40.0,12,68.0,Sincrónico,No
759,EST-2760,Bases de Datos SQL,Profesional,10.0,20,75.0,Asincrónico,Sí
792,EST-2793,Bases de Datos SQL,Profesional,15.5,18,NaN,Asincrónico,Sí
794,EST-2795,Bases de Datos SQL,Profesional,10.0,11,75.0,Híbrido,No
814,EST-2815,Bases de Datos SQL,Profesional,20.0,56,82.0,Asincrónico,Sí
839,EST-2840,Bases de Datos SQL,Profesional,25.0,26,NaN,Sincrónico,Sí
854,EST-2855,Bases de Datos SQL,Profesional,32.5,44,90.0,Híbrido,Sí
858,EST-2859,Bases de Datos SQL,Profesional,15.5,52,82.0,Asincrónico,No
879,EST-2880,Bases de Datos SQL,Profesional,40.0,42,NaN,Sincrónico,No
972,EST-2973,Bases de Datos SQL,Profesional,10.0,19,45.0,Asincrónico,Sí

In [ ]:
# Reemplazar los valores nulos de Horas_Estudio por el promedio
df_plataforma["Horas_Estudio"] = df_plataforma["Horas_Estudio"].fillna(
    df_plataforma["Horas_Estudio"].mean()
)

# Reemplazar los valores nulos de Puntaje_Evaluacion por 0.0
df_plataforma["Puntaje_Evaluacion"] = df_plataforma["Puntaje_Evaluacion"].fillna(0.0)

df_plataforma

,ID_Estudiante,Curso,Nivel_Educativo,Horas_Estudio,Lecciones_Completadas,Puntaje_Evaluacion,Modalidad,Certificado_Generado
0,EST-2001,Arquitectura Cloud,Profesional,20.0,26,82.0,Híbrido,Sí
1,EST-2002,Desarrollo Web,Técnico,10.0,27,0.0,Híbrido,Sí
2,EST-2003,Arquitectura Cloud,Técnico,40.0,25,90.0,Sincrónico,No
3,EST-2004,Desarrollo Web,Tecnólogo,20.0,55,68.0,Híbrido,Sí
4,EST-2005,Python para Datos,Técnico,50.0,46,45.0,Híbrido,No
...,...,...,...,...,...,...,...,...
1005,EST-2031,Python para Datos,Tecnólogo,25.0,26,82.0,Híbrido,Sí
1006,EST-2032,Inteligencia Artificial,Posgrado,40.0,34,0.0,Sincrónico,No
1007,EST-2033,Arquitectura Cloud,Técnico,20.0,15,75.0,Sincrónico,Sí
1008,EST-2034,Arquitectura Cloud,Técnico,15.5,13,82.0,Sincrónico,No
1009,EST-2035,Inteligencia Artificial,Posgrado,10.0,56,82.0,Asincrónico,Sí

In [48]:

def evaluar_nota(nota):
    return "Aprobado" if nota >= 70.0 else "Reprobado"


df_plataforma["Estado_Materia"] = df_plataforma["Puntaje_Evaluacion"].apply(evaluar_nota)


df_plataforma[["Puntaje_Evaluacion", "Estado_Materia"]]

      Puntaje_Evaluacion Estado_Materia
0                   82.0       Aprobado
1                    0.0      Reprobado
2                   90.0       Aprobado
3                   68.0      Reprobado
4                   45.0      Reprobado
...                  ...            ...
1005                82.0       Aprobado
1006                 0.0      Reprobado
1007                75.0       Aprobado
1008                82.0       Aprobado
1009                82.0       Aprobado

[1010 rows x 2 columns]

In [49]:
# Renombrar columnas
df_plataforma = df_plataforma.rename(columns={
    "Modalidad": "Formato_Clase",
    "Certificado_Generado": "Graduado"
})

# Ordenar columnas
columnas_ordenadas = ["Estado_Materia", "ID_Estudiante"] + [
    columna for columna in df_plataforma.columns
    if columna not in ["Estado_Materia", "ID_Estudiante"]
]

df_plataforma = df_plataforma[columnas_ordenadas]

df_plataforma

,Estado_Materia,ID_Estudiante,Curso,Nivel_Educativo,Horas_Estudio,Lecciones_Completadas,Puntaje_Evaluacion,Formato_Clase,Graduado
0,Aprobado,EST-2001,Arquitectura Cloud,Profesional,20.0,26,82.0,Híbrido,Sí
1,Reprobado,EST-2002,Desarrollo Web,Técnico,10.0,27,0.0,Híbrido,Sí
2,Aprobado,EST-2003,Arquitectura Cloud,Técnico,40.0,25,90.0,Sincrónico,No
3,Reprobado,EST-2004,Desarrollo Web,Tecnólogo,20.0,55,68.0,Híbrido,Sí
4,Reprobado,EST-2005,Python para Datos,Técnico,50.0,46,45.0,Híbrido,No
...,...,...,...,...,...,...,...,...,...
1005,Aprobado,EST-2031,Python para Datos,Tecnólogo,25.0,26,82.0,Híbrido,Sí
1006,Reprobado,EST-2032,Inteligencia Artificial,Posgrado,40.0,34,0.0,Sincrónico,No
1007,Aprobado,EST-2033,Arquitectura Cloud,Técnico,20.0,15,75.0,Sincrónico,Sí
1008,Aprobado,EST-2034,Arquitectura Cloud,Técnico,15.5,13,82.0,Sincrónico,No
1009,Aprobado,EST-2035,Inteligencia Artificial,Posgrado,10.0,56,82.0,Asincrónico,Sí

In [50]:
#Agrupar y calcular el promedio 

df_plataforma.groupby("Curso").agg({
    "Horas_Estudio": "mean",
    "Lecciones_Completadas": "sum"
})

                         Horas_Estudio  Lecciones_Completadas
Curso
Arquitectura Cloud           21.755578                   5928
Bases de Datos SQL           23.270550                   6846
Desarrollo Web               22.159650                   6856
Inteligencia Artificial      22.941284                   6626
Python para Datos            22.431403                   6283

In [51]:
def rango(series):
    return series.max() - series.min()

df_plataforma.groupby("Nivel_Educativo").agg({
    "Puntaje_Evaluacion": rango
})

                 Puntaje_Evaluacion
Nivel_Educativo
Posgrado                       98.0
Profesional                    98.0
Tecnólogo                      98.0
Técnico                        98.0

In [52]:
df_plataforma.groupby(["Curso", "Formato_Clase"]).agg({
    "Horas_Estudio": "sum",
    "Puntaje_Evaluacion": "mean"
})

                                       Horas_Estudio  Puntaje_Evaluacion
Curso                   Formato_Clase
Arquitectura Cloud      Asincrónico      1269.134472           70.542373
                        Híbrido          1636.096051           65.257143
                        Sincrónico       1293.596051           68.046875
Bases de Datos SQL      Asincrónico      1612.096051           67.589041
                        Híbrido          1459.038420           64.833333
                        Sincrónico       1676.057631           68.802817
Desarrollo Web          Asincrónico      1851.596051           66.345679
                        Híbrido          1497.653682           67.724638
                        Sincrónico       1348.596051           69.322581
Inteligencia Artificial Asincrónico      1548.615261           67.463768
                        Híbrido          1783.153682           70.324675
                        Sincrónico       1417.076841           68.114754
Python para Datos       Asincrónico      1642.076841           67.072464
                        Híbrido          1339.057631           69.754098
                        Sincrónico       1370.557631           66.265625